{ namespace, lib, config, pkgs, inputs, ... }:

with lib;
with lib.${namespace};
let
  cfg = config.${namespace}.browser.chromium;

  # Base16 colors generated by Stylix, applied globally to every page.
  colors = config.lib.stylix.colors.withHashtag;

  # Everything here is a small UI element (border/accent/caret/outline),
  # never page text/backgrounds, so a single fixed shade per role is fine.
  stylixGlobalCss = ''
    /* :root defaults: form-control accent, text-cursor color, scrollbar thumb/track. */
    :root {
      accent-color: ${colors.base0D};
      caret-color: ${colors.base0D} !important;
      scrollbar-color: ${colors.base03} transparent;
    }
    /* Links */
    a:link, a:visited {
      color: ${colors.base0D} !important;
    }
    /* Text-selection highlight only, not default page text. */
    ::selection {
      background-color: ${colors.base02} !important;
      color: ${colors.base05} !important;
    }
    /* Form control borders: text inputs/textareas, dropdowns, buttons. */
    input, select, button  {
      border-color: ${colors.base03} !important;
    }
    /* Misc structural borders: horizontal rules, tables/cells/headers, fieldset boxes, kbd keys, blockquotes. */
    hr, table, td, th, fieldset, kbd, blockquote {
      border-color: ${colors.base03} !important;
    }
    /* Keyboard-focus ring shown on the currently focused element. */
    :focus-visible {
      outline-color: ${colors.base0D} !important;
    }
  '';

  # Config record understood by Injectify's own `configs` storage schema
  # (see background.js: id/name/urlPattern/enabled/cssCode/jsCode/cdnUrls).
  stylixInjectifyConfig = pkgs.writeText "stylix-config.json" (builtins.toJSON [
    {
      id = "stylix-global-theme";
      name = "Stylix global theme (managed by Nix — do not edit)";
      urlPattern = "*";
      enabled = true;
      cssCode = stylixGlobalCss;
      jsCode = "";
      cdnUrls = [ ];
    }
  ]);

  # Appended (not patched in-place) so it survives upstream background.js changes:
  # on every browser startup/extension (re)install, overwrite our managed config
  # entry in Injectify's own chrome.storage.local, using its own storage API.
  stylixSyncScript = ''

    // --- Stylix auto-sync (declaratively managed by Nix — do not edit) ---
    (() => {
      const STYLIX_CONFIG_ID = 'stylix-global-theme';

      async function syncStylixConfig() {
        try {
          const res = await fetch(chrome.runtime.getURL('stylix-config.json'));
          const stylixConfigs = await res.json();
          const { configs } = await chrome.storage.local.get('configs');
          const rest = (configs || []).filter((c) => c.id !== STYLIX_CONFIG_ID);
          await chrome.storage.local.set({ configs: [...stylixConfigs, ...rest] });
        } catch (err) {
          console.error('[Injectify] Failed to sync Stylix config:', err);
        }
      }

      chrome.runtime.onStartup.addListener(syncStylixConfig);
      chrome.runtime.onInstalled.addListener(syncStylixConfig);
    })();
  '';

  injectifyStylixExtension = pkgs.runCommand "injectify-stylix" { } ''
    mkdir -p $out
    cp -r ${inputs.injectify}/extension/. $out/
    chmod -R u+w $out
    cp ${stylixInjectifyConfig} $out/stylix-config.json
    cat >> $out/background.js <<'EOF'
    ${stylixSyncScript}
    EOF
  '';
in
{
  options.${namespace}.browser.chromium = with types; {
    enable = mkBoolOpt false "Whether or not to enable chromium.";
    stylixTheme = mkBoolOpt true ''
      Whether to inject a Stylix-derived global theme into every page,
      using a vendored, patched copy of the open-source Injectify extension
      (github:shade-solutions/Injectify). Requires ${namespace}.stylix.enable.
    '';
  };

  config = mkIf cfg.enable {
    programs.chromium = {
      enable = true;
      package = pkgs.chromium.override {
        enableWideVine = true; # allows playing DRM-protected content (like Netflix, Spotify, or Amazon Prime)
      };
      extensions = [
        "epcnnfbjfcgphgdmggkamkmgojdagdnn" # ublock
        "dbepggeogbaibhgnhhndojpepiihcmeb" # vimium
        "khncfooichmfjbepaaaebmommgaepoid" # Unhook - Remove YouTube Recommended & Shorts
      ];
      commandLineArgs = [
        "--enable-features=TouchpadOverscrollHistoryNavigation" # use touchpad to navigate between pages
        "--enable-background-mode" # keep process alive after last window closes, so preload is always ready
      ] ++ optional (cfg.stylixTheme && config.${namespace}.stylix.enable)
        "--load-extension=${injectifyStylixExtension}";
    };
  };
}
