name: Check nix files are correctly formatted

on: [push, workflow_dispatch]

jobs:
  nixfmt:
    name: nixfmt format check
    if: false # dont use formatting, I dont like the formatted code stracture
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs && nix-channel --update
      - run: nix-env -iA nixpkgs.nixfmt-classic
      - run: nixfmt --check .
