on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

jobs:
  flakehub-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Necessary for authenticating against FlakeHub
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true # log in to flakehub for private flakes
      - uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: private # pushed flake repo visibility
